package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.pointlion.sys.mvc.common.base.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaApplyBuyItem<M extends BaseOaApplyBuyItem<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setBuyId(java.lang.String buyId) {
		set("buy_id", buyId);
	}
	
	public java.lang.String getBuyId() {
		return getStr("buy_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSupplyOrgName(java.lang.String supplyOrgName) {
		set("supply_org_name", supplyOrgName);
	}
	
	public java.lang.String getSupplyOrgName() {
		return getStr("supply_org_name");
	}

	public void setModelNum(java.lang.String modelNum) {
		set("model_num", modelNum);
	}
	
	public java.lang.String getModelNum() {
		return getStr("model_num");
	}

	public void setUnitPrice(java.lang.String unitPrice) {
		set("unit_price", unitPrice);
	}
	
	public java.lang.String getUnitPrice() {
		return getStr("unit_price");
	}

	public void setCount(java.lang.String count) {
		set("count", count);
	}
	
	public java.lang.String getCount() {
		return getStr("count");
	}

	public void setSumPrice(java.lang.String sumPrice) {
		set("sum_price", sumPrice);
	}
	
	public java.lang.String getSumPrice() {
		return getStr("sum_price");
	}

}
