package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaApplyFinance<M extends BaseOaApplyFinance<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setApplyerName(java.lang.String applyerName) {
		set("applyer_name", applyerName);
	}
	
	public java.lang.String getApplyerName() {
		return getStr("applyer_name");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}
	
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public void setLeaderMessage(java.lang.String leaderMessage) {
		set("leader_message", leaderMessage);
	}
	
	public java.lang.String getLeaderMessage() {
		return getStr("leader_message");
	}

	public void setLeader2Message(java.lang.String leader2Message) {
		set("leader2_message", leader2Message);
	}
	
	public java.lang.String getLeader2Message() {
		return getStr("leader2_message");
	}

	public void setIfSubmit(java.lang.String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public java.lang.String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(java.lang.String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public java.lang.String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(java.lang.String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public java.lang.String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(java.lang.String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public java.lang.String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}
	
	public java.lang.String getDes() {
		return getStr("des");
	}

	public void setReceiveMoneyOrgName(java.lang.String receiveMoneyOrgName) {
		set("receive_money_org_name", receiveMoneyOrgName);
	}
	
	public java.lang.String getReceiveMoneyOrgName() {
		return getStr("receive_money_org_name");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(java.lang.String project_name) {
		set("project_name", project_name);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}
	
	public void setFormProjectId(java.lang.String projectId) {
		set("formproject_id", projectId);
	}
	
	public java.lang.String getFormProjectId() {
		return getStr("formproject_id");
	}

	public void setFormProjectName(java.lang.String project_name) {
		set("formproject_name", project_name);
	}
	
	public java.lang.String getFormProjectName() {
		return getStr("formproject_name");
	}
	
	public void setContractId(java.lang.String contractId) {
		set("contract_id", contractId);
	}
	
	public java.lang.String getContractId() {
		return getStr("contract_id");
	}

	public void setContractNum(java.lang.String contractNum) {
		set("contract_num", contractNum);
	}
	
	public java.lang.String getContractNum() {
		return getStr("contract_num");
	}

	public void setContractAllPrice(java.lang.String contractAllPrice) {
		set("contract_all_price", contractAllPrice);
	}
	
	public java.lang.String getContractAllPrice() {
		return getStr("contract_all_price");
	}

	public void setResultPrice(java.lang.String resultPrice) {
		set("result_price", resultPrice);
	}
	
	public java.lang.String getResultPrice() {
		return getStr("result_price");
	}

	public void setToBeforeSumPay(java.lang.String toBeforeSumPay) {
		set("to_before_sum_pay", toBeforeSumPay);
	}
	
	public java.lang.String getToBeforeSumPay() {
		return getStr("to_before_sum_pay");
	}

	public void setNowApplyPayPrice(java.lang.String nowApplyPayPrice) {
		set("now_apply_pay_price", nowApplyPayPrice);
	}
	
	public java.lang.String getNowApplyPayPrice() {
		return getStr("now_apply_pay_price");
	}

	public void setToNowSumPay(java.lang.String toNowSumPay) {
		set("to_now_sum_pay", toNowSumPay);
	}
	
	public java.lang.String getToNowSumPay() {
		return getStr("to_now_sum_pay");
	}

	public void setSumPayRate(java.lang.String sumPayRate) {
		set("sum_pay_rate", sumPayRate);
	}
	
	public java.lang.String getSumPayRate() {
		return getStr("sum_pay_rate");
	}

	public void setToNowSumComplete(java.lang.String toNowSumComplete) {
		set("to_now_sum_complete", toNowSumComplete);
	}
	
	public java.lang.String getToNowSumComplete() {
		return getStr("to_now_sum_complete");
	}

	public void setTaxPriceName(java.lang.String taxPriceName) {
		set("tax_price_name", taxPriceName);
	}
	
	public java.lang.String getTaxPriceName() {
		return getStr("tax_price_name");
	}

	public void setTaxPrice(java.lang.String taxPrice) {
		set("tax_price", taxPrice);
	}
	
	public java.lang.String getTaxPrice() {
		return getStr("tax_price");
	}

	public void setLoanSumMoney(java.lang.String loanSumMoney) {
		set("loan_sum_money", loanSumMoney);
	}
	
	public java.lang.String getLoanSumMoney() {
		return getStr("loan_sum_money");
	}

	public void setLoadSumGiveMoney(java.lang.String loadSumGiveMoney) {
		set("load_sum_give_money", loadSumGiveMoney);
	}
	
	public java.lang.String getLoadSumGiveMoney() {
		return getStr("load_sum_give_money");
	}

	public void setToBoforeSumBackMoney(java.lang.String toBoforeSumBackMoney) {
		set("to_bofore_sum_back_money", toBoforeSumBackMoney);
	}
	
	public java.lang.String getToBoforeSumBackMoney() {
		return getStr("to_bofore_sum_back_money");
	}

	public void setNowApplyBackMoney(java.lang.String nowApplyBackMoney) {
		set("now_apply_back_money", nowApplyBackMoney);
	}
	
	public java.lang.String getNowApplyBackMoney() {
		return getStr("now_apply_back_money");
	}

	public void setToNowSumBackMoney(java.lang.String toNowSumBackMoney) {
		set("to_now_sum_back_money", toNowSumBackMoney);
	}
	
	public java.lang.String getToNowSumBackMoney() {
		return getStr("to_now_sum_back_money");
	}

	public void setCommonPriceName(java.lang.String commonPriceName) {
		set("common_price_name", commonPriceName);
	}
	
	public java.lang.String getCommonPriceName() {
		return getStr("common_price_name");
	}

	public void setCommonPrice(java.lang.String commonPrice) {
		set("common_price", commonPrice);
	}
	
	public java.lang.String getCommonPrice() {
		return getStr("common_price");
	}

	public void setBorrowUserName(java.lang.String borrowUserName) {
		set("borrow_user_name", borrowUserName);
	}
	
	public java.lang.String getBorrowUserName() {
		return getStr("borrow_user_name");
	}

	public void setBorrowReason(java.lang.String borrowReason) {
		set("borrow_reason", borrowReason);
	}
	
	public java.lang.String getBorrowReason() {
		return getStr("borrow_reason");
	}

	public void setChangeRenson(java.lang.String changeRenson) {
		set("change_renson", changeRenson);
	}
	
	public java.lang.String getChangeRenson() {
		return getStr("change_renson");
	}

	public void setChangeMoneyReceiveTime(java.lang.String changeMoneyReceiveTime) {
		set("change_money_receive_time", changeMoneyReceiveTime);
	}
	
	public java.lang.String getChangeMoneyReceiveTime() {
		return getStr("change_money_receive_time");
	}

	public void setChangeWay(java.lang.String changeWay) {
		set("change_way", changeWay);
	}
	
	public java.lang.String getChangeWay() {
		return getStr("change_way");
	}

	public void setChangeReceiveOrgid(java.lang.String changeReceiveOrgid) {
		set("change_receive_orgid", changeReceiveOrgid);
	}
	
	public java.lang.String getChangeReceiveOrgid() {
		return getStr("change_receive_orgid");
	}

	public void setChangeReceiveOrgname(java.lang.String changeReceiveOrgname) {
		set("change_receive_orgname", changeReceiveOrgname);
	}
	
	public java.lang.String getChangeReceiveOrgname() {
		return getStr("change_receive_orgname");
	}

	public void setChangeReceiveBankNum(java.lang.String changeReceiveBankNum) {
		set("change_receive_bank_num", changeReceiveBankNum);
	}
	
	public java.lang.String getChangeReceiveBankNum() {
		return getStr("change_receive_bank_num");
	}

	public void setChangeSendOrgid(java.lang.String changeSendOrgid) {
		set("change_send_orgid", changeSendOrgid);
	}
	
	public java.lang.String getChangeSendOrgid() {
		return getStr("change_send_orgid");
	}

	public void setChangeSendOrgname(java.lang.String changeSendOrgname) {
		set("change_send_orgname", changeSendOrgname);
	}
	
	public java.lang.String getChangeSendOrgname() {
		return getStr("change_send_orgname");
	}

	public void setChangeSendBankNum(java.lang.String changeSendBankNum) {
		set("change_send_bank_num", changeSendBankNum);
	}
	
	public java.lang.String getChangeSendBankNum() {
		return getStr("change_send_bank_num");
	}

	public void setChangeDes(java.lang.String changeDes) {
		set("change_des", changeDes);
	}
	
	public java.lang.String getChangeDes() {
		return getStr("change_des");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}
	
	public void setAboutOrgid(java.lang.String orgid) {
		set("about_orgid", orgid);
	}

	public java.lang.String getAboutOrgid() {
		return get("about_orgid");
	}
	
	public void setFinanceNum(java.lang.String finance_num) {
		set("finance_num", finance_num);
	}

	public java.lang.String getFinanceNum() {
		return get("finance_num");
	}
	
	public void setFinanceNumNum(java.lang.Integer finance_num_num) {
		set("finance_num_num", finance_num_num);
	}

	public java.lang.Integer getFinanceNumNum() {
		return get("finance_num_num");
	}
	
	public void setFinanceNumYear(java.lang.String finance_num_year) {
		set("finance_num_year", finance_num_year);
	}

	public java.lang.String getFinanceNumYear() {
		return get("finance_num_year");
	}
	
	public void setFinanceNumChildCompanyId(java.lang.String finance_num_child_company_id) {
		set("finance_num_child_company_id", finance_num_child_company_id);
	}

	public java.lang.String getFinanceNumChildCompanyId() {
		return get("finance_num_child_company_id");
	}
}
