package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaContractApply<M extends BaseOaContractApply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setApplyerName(java.lang.String applyerName) {
		set("applyer_name", applyerName);
	}
	
	public java.lang.String getApplyerName() {
		return getStr("applyer_name");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}
	
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public void setLeaderMessage(java.lang.String leaderMessage) {
		set("leader_message", leaderMessage);
	}
	
	public java.lang.String getLeaderMessage() {
		return getStr("leader_message");
	}

	public void setLeader2Message(java.lang.String leader2Message) {
		set("leader2_message", leader2Message);
	}
	
	public java.lang.String getLeader2Message() {
		return getStr("leader2_message");
	}

	public void setIfSubmit(java.lang.String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public java.lang.String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(java.lang.String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public java.lang.String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(java.lang.String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public java.lang.String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(java.lang.String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public java.lang.String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}
	
	public java.lang.String getDes() {
		return getStr("des");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCustomName(java.lang.String customName) {
		set("custom_name", customName);
	}
	
	public java.lang.String getCustomName() {
		return getStr("custom_name");
	}

	public void setCustomContactPerson(java.lang.String customContactPerson) {
		set("custom_contact_person", customContactPerson);
	}
	
	public java.lang.String getCustomContactPerson() {
		return getStr("custom_contact_person");
	}

	public void setCustomContactMobile(java.lang.String customContactMobile) {
		set("custom_contact_mobile", customContactMobile);
	}
	
	public java.lang.String getCustomContactMobile() {
		return getStr("custom_contact_mobile");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setType2(java.lang.String type) {
		set("type2", type);
	}
	
	public java.lang.String getType2() {
		return getStr("type2");
	}
	
	public void setAmountOfMoney(java.lang.String amountOfMoney) {
		set("amount_of_money", amountOfMoney);
	}
	
	public java.lang.String getAmountOfMoney() {
		return getStr("amount_of_money");
	}

	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public void setBackground(java.lang.String background) {
		set("background", background);
	}
	
	public java.lang.String getBackground() {
		return getStr("background");
	}

	public void setNeed(java.lang.String need) {
		set("need", need);
	}
	
	public java.lang.String getNeed() {
		return getStr("need");
	}

	public void setWorkTogether(java.lang.String workTogether) {
		set("work_together", workTogether);
	}
	
	public java.lang.String getWorkTogether() {
		return getStr("work_together");
	}

	public void setAddExt(java.lang.String addExt) {
		set("add_ext", addExt);
	}
	
	public java.lang.String getAddExt() {
		return getStr("add_ext");
	}

	public void setDangerNeed(java.lang.String dangerNeed) {
		set("danger_need", dangerNeed);
	}
	
	public java.lang.String getDangerNeed() {
		return getStr("danger_need");
	}

	public void setDangerNeedNoOk(java.lang.String dangerNeedNoOk) {
		set("danger_need_no_ok", dangerNeedNoOk);
	}
	
	public java.lang.String getDangerNeedNoOk() {
		return getStr("danger_need_no_ok");
	}

	public void setDangerPayHard(java.lang.String dangerPayHard) {
		set("danger_pay_hard", dangerPayHard);
	}
	
	public java.lang.String getDangerPayHard() {
		return getStr("danger_pay_hard");
	}

	public void setDangerLaw(java.lang.String dangerLaw) {
		set("danger_law", dangerLaw);
	}
	
	public java.lang.String getDangerLaw() {
		return getStr("danger_law");
	}

	public void setDangerExt(java.lang.String dangerExt) {
		set("danger_ext", dangerExt);
	}
	
	public java.lang.String getDangerExt() {
		return getStr("danger_ext");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}
	
	public void setCanAbleDate(java.lang.String can_able_date) {
		set("can_able_date", can_able_date);
	}

	public java.lang.String getCanAbleDate() {
		return get("can_able_date");
	}
	
	
	
	
	
	public void setContractNum(java.lang.String contract_num) {
		set("contract_num", contract_num);
	}

	public java.lang.String getContractNum() {
		return get("contract_num");
	}
	
	public void setContractNumNum(java.lang.Integer contract_num_num) {
		set("contract_num_num", contract_num_num);
	}

	public java.lang.Integer getContractNumNum() {
		return get("contract_num_num");
	}
	
	public void setContractNumYear(java.lang.String contract_num_year) {
		set("contract_num_year", contract_num_year);
	}

	public java.lang.String getContractNumYear() {
		return get("contract_num_year");
	}
	
	public void setContractNumChildCompanyId(java.lang.String contract_num_child_company_id) {
		set("contract_num_child_company_id", contract_num_child_company_id);
	}

	public java.lang.String getContractNumChildCompanyId() {
		return get("contract_num_child_company_id");
	}
}
