package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrapZiboEnvironmentGas<M extends BaseGrapZiboEnvironmentGas<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setMonitorTime(java.lang.String monitorTime) {
		set("monitor_time", monitorTime);
	}
	
	public java.lang.String getMonitorTime() {
		return getStr("monitor_time");
	}

	public void setSo2Shicenongdu(java.lang.String so2Shicenongdu) {
		set("so2_shicenongdu", so2Shicenongdu);
	}
	
	public java.lang.String getSo2Shicenongdu() {
		return getStr("so2_shicenongdu");
	}

	public void setSo2Zhesuannongdu(java.lang.String so2Zhesuannongdu) {
		set("so2_zhesuannongdu", so2Zhesuannongdu);
	}
	
	public java.lang.String getSo2Zhesuannongdu() {
		return getStr("so2_zhesuannongdu");
	}

	public void setSo2Paifangliang(java.lang.String so2Paifangliang) {
		set("so2_paifangliang", so2Paifangliang);
	}
	
	public java.lang.String getSo2Paifangliang() {
		return getStr("so2_paifangliang");
	}

	public void setNooShicenongdu(java.lang.String nooShicenongdu) {
		set("noo_shicenongdu", nooShicenongdu);
	}
	
	public java.lang.String getNooShicenongdu() {
		return getStr("noo_shicenongdu");
	}

	public void setNooZhesuannongdu(java.lang.String nooZhesuannongdu) {
		set("noo_zhesuannongdu", nooZhesuannongdu);
	}
	
	public java.lang.String getNooZhesuannongdu() {
		return getStr("noo_zhesuannongdu");
	}

	public void setNooPaifangliang(java.lang.String nooPaifangliang) {
		set("noo_paifangliang", nooPaifangliang);
	}
	
	public java.lang.String getNooPaifangliang() {
		return getStr("noo_paifangliang");
	}

	public void setPelletShicenongdu(java.lang.String pelletShicenongdu) {
		set("pellet_shicenongdu", pelletShicenongdu);
	}
	
	public java.lang.String getPelletShicenongdu() {
		return getStr("pellet_shicenongdu");
	}

	public void setPelletZhesuannongdu(java.lang.String pelletZhesuannongdu) {
		set("pellet_zhesuannongdu", pelletZhesuannongdu);
	}
	
	public java.lang.String getPelletZhesuannongdu() {
		return getStr("pellet_zhesuannongdu");
	}

	public void setPelletPaifangliang(java.lang.String pelletPaifangliang) {
		set("pellet_paifangliang", pelletPaifangliang);
	}
	
	public java.lang.String getPelletPaifangliang() {
		return getStr("pellet_paifangliang");
	}

	public void setYanghangliang(java.lang.String yanghangliang) {
		set("yanghangliang", yanghangliang);
	}
	
	public java.lang.String getYanghangliang() {
		return getStr("yanghangliang");
	}

	public void setYanqiwendu(java.lang.String yanqiwendu) {
		set("yanqiwendu", yanqiwendu);
	}
	
	public java.lang.String getYanqiwendu() {
		return getStr("yanqiwendu");
	}

	public void setFeiqipaifangliang(java.lang.String feiqipaifangliang) {
		set("feiqipaifangliang", feiqipaifangliang);
	}
	
	public java.lang.String getFeiqipaifangliang() {
		return getStr("feiqipaifangliang");
	}

	public void setLutangshangbuduanmian(java.lang.String lutangshangbuduanmian) {
		set("lutangshangbuduanmian", lutangshangbuduanmian);
	}
	
	public java.lang.String getLutangshangbuduanmian() {
		return getStr("lutangshangbuduanmian");
	}

}
