package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDctResourceMeetroot<M extends BaseDctResourceMeetroot<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setRoomNum(java.lang.String roomNum) {
		set("room_num", roomNum);
	}
	
	public java.lang.String getRoomNum() {
		return getStr("room_num");
	}

	public void setFloorNum(java.lang.String floorNum) {
		set("floor_num", floorNum);
	}
	
	public java.lang.String getFloorNum() {
		return getStr("floor_num");
	}

	public void setBuilding(java.lang.String building) {
		set("building", building);
	}
	
	public java.lang.String getBuilding() {
		return getStr("building");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}
	
	public java.lang.String getDes() {
		return getStr("des");
	}

}
