package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrapUrlCol<M extends BaseGrapUrlCol<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUrlId(java.lang.String urlId) {
		set("url_id", urlId);
	}
	
	public java.lang.String getUrlId() {
		return getStr("url_id");
	}

	public void setPattern(java.lang.String pattern) {
		set("pattern", pattern);
	}
	
	public java.lang.String getPattern() {
		return getStr("pattern");
	}

	public void setDbId(java.lang.String dbId) {
		set("db_id", dbId);
	}
	
	public java.lang.String getDbId() {
		return getStr("db_id");
	}

	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}
	
	public java.lang.String getTableName() {
		return getStr("table_name");
	}

	public void setColName(java.lang.String colName) {
		set("col_name", colName);
	}
	
	public java.lang.String getColName() {
		return getStr("col_name");
	}

	public void setColDataType(java.lang.String colDataType) {
		set("col_data_type", colDataType);
	}
	
	public java.lang.String getColDataType() {
		return getStr("col_data_type");
	}

	public void setColDateFormat(java.lang.String colDateFormat) {
		set("col_date_format", colDateFormat);
	}
	
	public java.lang.String getColDateFormat() {
		return getStr("col_date_format");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

}
