package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaProjectBuild<M extends BaseOaProjectBuild<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setApplyerName(java.lang.String applyerName) {
		set("applyer_name", applyerName);
	}
	
	public java.lang.String getApplyerName() {
		return getStr("applyer_name");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}
	
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public void setLeaderMessage(java.lang.String leaderMessage) {
		set("leader_message", leaderMessage);
	}
	
	public java.lang.String getLeaderMessage() {
		return getStr("leader_message");
	}

	public void setLeader2Message(java.lang.String leader2Message) {
		set("leader2_message", leader2Message);
	}
	
	public java.lang.String getLeader2Message() {
		return getStr("leader2_message");
	}

	public void setIfSubmit(java.lang.String ifSubmit) {
		set("if_submit", ifSubmit);
	}
	
	public java.lang.String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(java.lang.String ifComplete) {
		set("if_complete", ifComplete);
	}
	
	public java.lang.String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(java.lang.String ifAgree) {
		set("if_agree", ifAgree);
	}
	
	public java.lang.String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(java.lang.String procInsId) {
		set("proc_ins_id", procInsId);
	}
	
	public java.lang.String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public void setLeader(java.lang.String leader) {
		set("leader", leader);
	}
	
	public java.lang.String getLeader() {
		return getStr("leader");
	}
	
	public void setMember(java.lang.String member) {
		set("member", member);
	}
	
	public java.lang.String getMember() {
		return getStr("member");
	}
	
	
	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
	}
	
	public java.lang.String getCustomerName() {
		return getStr("customer_name");
	}

	public void setCustomerContactName(java.lang.String customerContactName) {
		set("customer_contact_name", customerContactName);
	}
	
	public java.lang.String getCustomerContactName() {
		return getStr("customer_contact_name");
	}

	public void setCustomerContactMobile(java.lang.String customerContactMobile) {
		set("customer_contact_mobile", customerContactMobile);
	}
	
	public java.lang.String getCustomerContactMobile() {
		return getStr("customer_contact_mobile");
	}

	public void setActSuggest(java.lang.String actSuggest) {
		set("act_suggest", actSuggest);
	}
	
	public java.lang.String getActSuggest() {
		return getStr("act_suggest");
	}

	public void setCustomHope(java.lang.String custom_hope) {
		set("custom_hope", custom_hope);
	}
	
	public java.lang.String getCustomHope() {
		return getStr("custom_hope");
	}

	public void setRiskAndMeasure(java.lang.String riskAndMeasure) {
		set("risk_and_measure", riskAndMeasure);
	}
	
	public java.lang.String getRiskAndMeasure() {
		return getStr("risk_and_measure");
	}

	public void setActAllStrategySuggest(java.lang.String actAllStrategySuggest) {
		set("act_all_strategy_suggest", actAllStrategySuggest);
	}
	
	public java.lang.String getActAllStrategySuggest() {
		return getStr("act_all_strategy_suggest");
	}

	public void setContactName(java.lang.String contactName) {
		set("contact_name", contactName);
	}
	
	public java.lang.String getContactName() {
		return getStr("contact_name");
	}

	public void setContactMobile(java.lang.String contactMobile) {
		set("contact_mobile", contactMobile);
	}
	
	public java.lang.String getContactMobile() {
		return getStr("contact_mobile");
	}

	public void setContactMail(java.lang.String contactMail) {
		set("contact_mail", contactMail);
	}
	
	public java.lang.String getContactMail() {
		return getStr("contact_mail");
	}

	public void setProjectStartTime(java.lang.String project_start_time) {
		set("project_start_time", project_start_time);
	}
	
	public java.lang.String getProjectStartTime() {
		return getStr("project_start_time");
	}
	
	public void setProjectMoney(java.lang.String project_money) {
		set("project_money", project_money);
	}
	
	public java.lang.String getProjectMoney() {
		return getStr("project_money");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}
}
