package com.lion.sys.mvc.menu;

import java.util.ArrayList;
import java.util.List;

import com.lion.sys.dto.LayTreeNode;
import com.lion.sys.mvc.base.model.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu();
	/***
	 * 根据id 查询孩子
	 * @param id
	 * @return
	 */
	public List<SysMenu> getChildrenById(String id){
		return SysMenu.dao.find("select * from sys_menu m where m.parent_id='"+id+"'");
	}
	/***
	 * 菜单转成LayTreeNode
	 * @param menu
	 * @return
	 */
	public LayTreeNode toLayTreeNode(SysMenu menu){
		LayTreeNode node = new LayTreeNode();
		node.setId(menu.getId());
		node.setName(menu.getName());
//		node.setChildren(children);
		return node;
	}
	/***
	 * 菜单转成LayTreeNode
	 * @param menu
	 * @return
	 */
	public List<LayTreeNode> toLayTreeNode(List<SysMenu> menuList){
		List<LayTreeNode> list = new ArrayList<LayTreeNode>();
		for(SysMenu menu : menuList){
			LayTreeNode node = toLayTreeNode(menu);
			node.setChildren(toLayTreeNode(menu.getChildren()));
			list.add(node);
		}
		return list;
	}
	/***
	 * 获取所有菜单
	 * @return
	 */
	public List<SysMenu> getAllMenu(){
		List<SysMenu> list =  getChildren("#root");
		return list;
	}
	/***
	 * 递归
	 * 查询孩子
	 * @param id
	 * @return
	 */
	public List<SysMenu> getChildren(String id){
		System.out.println("************赵孩子****************");
		List<SysMenu> menuList =  getChildrenById(id);//根据id查询孩子
		for(SysMenu m : menuList){
			System.out.println(m.getName());
			m.setChildren(getChildren(m.getId()));
		}
		return menuList;
	}
	

}
