package com.lion.sys.mvc.menu;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.lion.sys.dto.LayTreeNode;
import com.lion.sys.mvc.base.model.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {


	public static final SysMenu dao = new SysMenu();
	/***
	 * 根据主键查询
	 */
	public SysMenu getById(String id){
		return SysMenu.dao.findById(id);
	}
	/***
	 * 根据id 查询孩子
	 * @param id
	 * @return
	 */
	public List<SysMenu> getChildrenByPid(String id){
		return SysMenu.dao.find("select * from sys_menu m where m.parent_id='"+id+"' order by m.sort");
	}
	/***
	 * 根据id 查询孩子分页
	 * @param id
	 * @return
	 */
	public Page<Record> getChildrenPageByPid(int pnum,int psize, String pid){
		return Db.paginate(pnum, psize, "select m.* , o.name oname , o.url url ", " from sys_menu m LEFT JOIN sys_operate o ON m.operatorid = o.id WHERE m.parent_id='"+pid+"' order by m.sort");
	}
	/***
	 * 菜单转成LayTreeNode
	 * @param menu
	 * @return
	 */
	public LayTreeNode toLayTreeNode(SysMenu menu){
		LayTreeNode node = new LayTreeNode();
		node.setId(menu.getId());
		node.setName(menu.getName());
//		node.setChildren(children);
		return node;
	}
	/***
	 * 菜单转成LayTreeNode
	 * @param menu
	 * @return
	 */
	public List<LayTreeNode> toLayTreeNode(List<SysMenu> menuList,Boolean spread){
		List<LayTreeNode> list = new ArrayList<LayTreeNode>();
		for(SysMenu menu : menuList){
			LayTreeNode node = toLayTreeNode(menu);
			if(menu.getChildren()!=null&&menu.getChildren().size()>0){
				node.setChildren(toLayTreeNode(menu.getChildren(),spread));
			}
			node.setSpread(spread);
			list.add(node);
		}
		return list;
	}
	/***
	 * 获取所有菜单
	 * @return
	 */
	public List<SysMenu> getAllMenu(){
		List<SysMenu> list =  getChildrenAll("#root");
		return list;
	}
	/***
	 * 递归
	 * 查询孩子
	 * @param id
	 * @return
	 */
	public List<SysMenu> getChildrenAll(String id){
		List<SysMenu> menuList =  getChildrenByPid(id);//根据id查询孩子
		for(SysMenu m : menuList){
			System.out.println(m.getName());
			m.setChildren(getChildrenAll(m.getId()));
		}
		return menuList;
	}
	
	/***
	 * 获取我的菜单
	 * @param userid
	 * @return
	 */
	public List<Record> getMenuByUserId(String userid){
		List<Record> result = new ArrayList<Record>();//返回结果
		List<Record> rootList = Db.find("select * from sys_menu m where m.parent_id='#root' order by m.sort");//根目录树结构
		for(Record m : rootList){
			List<Record> childList = Db.find("SELECT 	 m.*,o.url url FROM sys_menu m,	sys_userrole u,	sys_role r,	sys_roleoperator ro,sys_operate o WHERE	m.operatorid = o.id AND o.id = ro.operator_id AND ro.role_id = r.id AND u.role_id = r.id AND u.user_id = '"+userid+"' AND m.parent_id = '"+m.getStr("id")+"' order by m.sort");
			if(childList!=null&&childList.size()>0){//有孩子
				m.set("children", childList);
				result.add(m);
			}
		}
		return result;
	}

}
