package com.lion.sys.mvc.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.lion.sys.mvc.menu.SysMenu;
import com.lion.sys.mvc.module.SysModule;

import java.util.List;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysModule<M extends BaseSysModule<M>> extends Model<M> implements IBean {
	private List<SysModule> children;
	
	public List<SysModule> getChildren() {
		return children;
	}
	public void setChildren(List<SysModule> children) {
		this.children = children;
	}
	
	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setIsparent(java.lang.String isparent) {
		set("isparent", isparent);
	}

	public java.lang.String getIsparent() {
		return get("isparent");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}

	public java.lang.Long getSort() {
		return get("sort");
	}

	public void setParentId(java.lang.String parentmoduleids) {
		set("parent_id", parentmoduleids);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setSystemid(java.lang.String systemid) {
		set("system_id", systemid);
	}

	public java.lang.String getSystemid() {
		return get("system_id");
	}

}
