package com.lion.sys.mvc.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOperate<M extends BaseSysOperate<M>> extends Model<M> implements IBean {

	public void setPermission(java.lang.String permission){
		set("permission",permission);
	}
	
	public java.lang.String getPermission(){
		return get("permission");
	}
	
	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOneMany(java.lang.String oneMany) {
		set("one_many", oneMany);
	}

	public java.lang.String getOneMany() {
		return get("one_many");
	}

	public void setReturnUrl(java.lang.String returnUrl) {
		set("return_url", returnUrl);
	}

	public java.lang.String getReturnUrl() {
		return get("return_url");
	}

	public void setRowFilter(java.lang.String rowFilter) {
		set("row_filter", rowFilter);
	}

	public java.lang.String getRowFilter() {
		return get("row_filter");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setModuleId(java.lang.String moduleId) {
		set("module_id", moduleId);
	}

	public java.lang.String getModuleId() {
		return get("module_id");
	}

	public void setFormToken(java.lang.String formToken) {
		set("form_token", formToken);
	}

	public java.lang.String getFormToken() {
		return get("form_token");
	}

	public void setIpBlack(java.lang.String ipBlack) {
		set("ip_black", ipBlack);
	}

	public java.lang.String getIpBlack() {
		return get("ip_black");
	}

	public void setPrivilegess(java.lang.String privilegess) {
		set("privilegess", privilegess);
	}

	public java.lang.String getPrivilegess() {
		return get("privilegess");
	}

	public void setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
	}

	public java.lang.String getModuleName() {
		return get("module_name");
	}
	public void setSort(java.lang.String sort) {
		set("sort", sort);
	}

	public java.lang.String getSort() {
		return get("sort");
	}
}
