package com.lion.sys.mvc.workflow.model;

import com.jfinal.plugin.activerecord.Page;
import com.lion.sys.mvc.base.model.BaseActReModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActReModel extends BaseActReModel<ActReModel> {
	public static final ActReModel dao = new ActReModel();
	/***
	 * 查询分页
	 * @param curr
	 * @param pagesize
	 * @return
	 */
	public Page<ActReModel> getModelPage(Integer curr , Integer pagesize){
		return ActReModel.dao.paginate(curr, pagesize, "select * ", " from act_re_model");
	}
}
