package com.lion.sys.mvc.operate;

import org.apache.commons.lang3.StringUtils;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.lion.sys.mvc.base.model.BaseSysOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperate extends BaseSysOperate<SysOperate> {
	public static final SysOperate dao = new SysOperate();
	
	/***
	 * 根据主键获取对象
	 * @param id
	 * @return
	 */
	public SysOperate getById(String id){
		return SysOperate.dao.findById(id);
	}
	public Page<Record> getPage(int pnum,int psize,String mid){
		String sql = " from sys_operate o , sys_module m where o.module_id = m.id ";
		if(StringUtils.isNotBlank(mid)){
			sql = sql + " and o.module_id = '"+mid+"'";
		}
		sql = sql + " order by o.sort";
		return Db.paginate(pnum, psize, "select m.name mname,o.* ", sql);
	}
}
