package com.lion.sys.mvc.operate;

import com.lion.sys.mvc.base.model.BaseSysOperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperator extends BaseSysOperator<SysOperator> {
	public static final SysOperator dao = new SysOperator();
}
