package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseActEvtLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActEvtLog extends BaseActEvtLog<ActEvtLog> {
	public static final ActEvtLog dao = new ActEvtLog().dao();
}
