package com.pointlion.sys.mvc.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.pointlion.sys.mvc.common.model.base.BaseActReModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActReModel extends BaseActReModel<ActReModel> {
	public static final ActReModel dao = new ActReModel();
	/***
	 * 查询分页
	 * @param curr
	 * @param pagesize
	 * @return
	 */
	public Page<ActReModel> getModelPage(Integer curr , Integer pagesize){
		return ActReModel.dao.paginate(curr, pagesize, "select * ", " FROM (select *  from act_re_model ORDER BY VERSION_ DESC) a group by KEY_");
	}
}
