package com.pointlion.sys.mvc.common.model;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Map;

import org.apache.poi.xwpf.usermodel.XWPFDocument;

import com.jfinal.plugin.activerecord.Page;
import com.pointlion.sys.mvc.common.model.base.BaseOaBumph;
import com.pointlion.sys.mvc.common.utils.POITemplateUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaBumph extends BaseOaBumph<OaBumph> {
	public static final OaBumph dao = new OaBumph();
	
	/***
	 * 获取分页
	 */
	public Page<OaBumph> getPage(int pnum,int psize){
		return OaBumph.dao.paginate(pnum, psize, "select b.*,p.PROC_DEF_ID_ defid", " from oa_bumph b LEFT JOIN act_hi_procinst p ON b.proc_ins_id=p.ID_ ORDER BY create_time DESC");
	}
	
	
	
	/***
	* 
	* @param params   数据
	* @param tmptUrl  模版路径
	* @param writeUrl 写出路径
	* @throws Exception
	*/
    public void bumphExport(Map<String, Object> params,String tmptUrl,String writeUrl) throws Exception{
	      InputStream is = new FileInputStream(tmptUrl);  
	      XWPFDocument doc = new XWPFDocument(is);  
	      //替换段落里面的变量  
	      POITemplateUtil.replaceQueInPara(doc, params);  
	      //替换表格里面的变量  
	      POITemplateUtil.replaceQueInTable(doc, params);  
	      OutputStream os = new FileOutputStream(writeUrl);  
	      doc.write(os);  
	      POITemplateUtil.close(os);  
	      POITemplateUtil.close(is);  
    }
}
