package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaBumphOrgUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaBumphOrgUser extends BaseOaBumphOrgUser<OaBumphOrgUser> {
	public static final OaBumphOrgUser dao = new OaBumphOrgUser();
}
