package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaResGet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaResGet extends BaseOaResGet<OaResGet> {
	public static final OaResGet dao = new OaResGet().dao();
}
