package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.pointlion.sys.mvc.common.model.base.BaseSysRoleoperator;




/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleAuth extends BaseSysRoleoperator<SysRoleAuth> {
	public static final SysRoleAuth dao = new SysRoleAuth();
	
	public List<SysRoleAuth> getByRoleidAndMenuid(String roleid,String menuid){
		return  SysRoleAuth.dao.find("select * from sys_role_auth o where o.role_id='"+roleid+"' and o.menu_id='"+menuid+"'");
	} 
}
