package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseVTasklist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VTasklist extends BaseVTasklist<VTasklist> {
	public static final VTasklist dao = new VTasklist();
}
