package com.pointlion.mvc.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.pointlion.mvc.common.model.OaNotice;
import com.pointlion.mvc.common.model.base.BaseCmsContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsContent extends BaseCmsContent<CmsContent> {
	public static final CmsContent dao = new CmsContent();
	
	public Page<OaNotice> getPage(int pnum,int psize,String type){
		return OaNotice.dao.paginate(pnum, psize, "select * "," FROM cms_content n where n.type='"+type+"' ORDER BY n.create_time DESC");
	}
}
