package com.pointlion.mvc.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.pointlion.mvc.common.model.base.BaseCmsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsType extends BaseCmsType<CmsType> {
	public static final CmsType dao = new CmsType();
	
	/***
	 * 获取所有的分组
	 * @return
	 */
	public List<Record> getAllGroup(){
		return Db.find("select * from cms_group g where g.type='special'");
	}
}
