package com.pointlion.mvc.common.model;

import com.pointlion.mvc.common.model.base.BaseSysPoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPoint extends BaseSysPoint<SysPoint> {
	public static final SysPoint dao = new SysPoint();
	
	/***
	 * 根据具类型获取积分
	 * @param type
	 * @return
	 */
	public SysPoint getByType(String type){
		return SysPoint.dao.findFirst("select * from sys_point p where p.type='"+type+"'");
	}
}
