package com.pointlion.mvc.common.model;

import com.pointlion.mvc.common.model.base.BaseSysRoleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleUser extends BaseSysRoleUser<SysRoleUser> {
	public static final SysRoleUser dao = new SysRoleUser();
	public static final String tableName = "sys_role_user";
	
	/***
	 * 查询
	 * @param userid
	 * @param roleid
	 * @return
	 */
	public SysRoleUser getByUseridAndRoleid(String userid, String roleid){
		return dao.findFirst("select * from sys_role_user ur where ur.role_id='"+roleid+"' and ur.user_id='"+userid+"'");
	}
}
