package com.pointlion.mvc.common.model;

import java.util.List;

import com.pointlion.mvc.common.model.base.BaseSysRoleMenu;




/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
	public static final SysRoleMenu dao = new SysRoleMenu();
	
	public List<SysRoleMenu> getByRoleidAndMenuid(String roleid, String menuid){
		return  SysRoleMenu.dao.find("select * from sys_role_menu o where o.role_id='"+roleid+"' and o.menu_id='"+menuid+"'");
	} 
}
