package com.pointlion.mvc.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.pointlion.mvc.common.model.base.BaseVTasklist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VTasklist extends BaseVTasklist<VTasklist> {
	public static final VTasklist dao = new VTasklist();
	public static final String tableName = "v_tasklist";
	
	/***
	 * 查询流程待办任务
	 */
	public VTasklist getTaskRecord(String id){
		return VTasklist.dao.findFirst("SELECT * FROM "+tableName+" t WHERE t.TASKID='"+id+"'");
	}
	
	public Record getActTaskById(String taskid){
		return Db.findFirst("select * from act_hi_taskinst t where t.id_='"+taskid+"'");
	}
}
