package com.pointlion.sys.mvc.admin.user;

import com.pointlion.sys.mvc.common.base.model.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	public static final SysUserRole dao = new SysUserRole();
}
