package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRoleOrg<M extends BaseSysRoleOrg<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setOrgId(String orgId) {
		set("org_id", orgId);
	}
	
	public String getOrgId() {
		return getStr("org_id");
	}

	public void setRoleId(String roleId) {
		set("role_id", roleId);
	}
	
	public String getRoleId() {
		return getStr("role_id");
	}

}
