package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysPointUser<M extends BaseSysPointUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public void setPoint(java.lang.Integer point) {
		set("point", point);
	}

	public java.lang.Integer getPoint() {
		return get("point");
	}
	
	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return get("reason");
	}
	
	public void setReceiveContentId(java.lang.String receive_content_id) {
		set("receive_content_id", receive_content_id);
	}

	public java.lang.String getReceiveContentId() {
		return get("receive_content_id");
	}
	
	public void setSignDay(java.lang.String signDay) {
		set("sign_day", signDay);
	}

	public java.lang.String getSignDay() {
		return get("sign_day");
	}

	public void setCreateDate(java.lang.String createDate) {
		set("create_date", createDate);
	}

	public java.lang.String getCreateDate() {
		return get("create_date");
	}
}
