package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSchJobExecute<M extends BaseSchJobExecute<M>> extends Model<M> implements IBean {

	public void setID(String ID) {
		set("ID", ID);
	}
	
	public String getID() {
		return getStr("ID");
	}

	public void setJobId(String jobId) {
		set("JOB_ID", jobId);
	}
	
	public String getJobId() {
		return getStr("JOB_ID");
	}

	public void setIsEnable(String isEnable) {
		set("IS_ENABLE", isEnable);
	}
	
	public String getIsEnable() {
		return getStr("IS_ENABLE");
	}

	public void setIsAutoRun(String isAutoRun) {
		set("IS_AUTO_RUN", isAutoRun);
	}
	
	public String getIsAutoRun() {
		return getStr("IS_AUTO_RUN");
	}

	public void setExePression(String exePression) {
		set("EXE_PRESSION", exePression);
	}
	
	public String getExePression() {
		return getStr("EXE_PRESSION");
	}

	public void setExeName(String exeName) {
		set("EXE_NAME", exeName);
	}
	
	public String getExeName() {
		return getStr("EXE_NAME");
	}

	public void setGROUP(String GROUP) {
		set("GROUP", GROUP);
	}
	
	public String getGROUP() {
		return getStr("GROUP");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}
	
}
