package com.pointlion.mvc.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaApplyCustom<M extends BaseOaApplyCustom<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return getStr("id");
	}

	public void setUserid(String userid) {
		set("userid", userid);
	}

	public String getUserid() {
		return getStr("userid");
	}

	public void setApplyerName(String applyerName) {
		set("applyer_name", applyerName);
	}

	public String getApplyerName() {
		return getStr("applyer_name");
	}

	public void setOrgId(String orgId) {
		set("org_id", orgId);
	}

	public String getOrgId() {
		return getStr("org_id");
	}

	public void setOrgName(String orgName) {
		set("org_name", orgName);
	}

	public String getOrgName() {
		return getStr("org_name");
	}

	public void setLeaderMessage(String leaderMessage) {
		set("leader_message", leaderMessage);
	}

	public String getLeaderMessage() {
		return getStr("leader_message");
	}

	public void setLeader2Message(String leader2Message) {
		set("leader2_message", leader2Message);
	}

	public String getLeader2Message() {
		return getStr("leader2_message");
	}

	public void setIfSubmit(String ifSubmit) {
		set("if_submit", ifSubmit);
	}

	public String getIfSubmit() {
		return getStr("if_submit");
	}

	public void setIfComplete(String ifComplete) {
		set("if_complete", ifComplete);
	}

	public String getIfComplete() {
		return getStr("if_complete");
	}

	public void setIfAgree(String ifAgree) {
		set("if_agree", ifAgree);
	}

	public String getIfAgree() {
		return getStr("if_agree");
	}

	public void setProcInsId(String procInsId) {
		set("proc_ins_id", procInsId);
	}

	public String getProcInsId() {
		return getStr("proc_ins_id");
	}

	public void setCreateTime(String createTime) {
		set("create_time", createTime);
	}

	public String getCreateTime() {
		return getStr("create_time");
	}

	public void setDes(String des) {
		set("des", des);
	}

	public String getDes() {
		return getStr("des");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setReason(String reason) {
		set("reason", reason);
	}

	public String getReason() {
		return getStr("reason");
	}

	public void setDefKey(String def_key) {
		set("def_key", def_key);
	}

	public String getDefKey() {
		return getStr("def_key");
	}

	public void setDefName(String name) {
		set("def_name", name);
	}

	public String getDefName() {
		return getStr("def_name");
	}
}
