package com.pointlion.sys.mvc.admin.chat;

import java.util.List;

import com.pointlion.sys.mvc.admin.user.SysUser;
import com.pointlion.sys.mvc.base.model.BaseSysFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFriend extends BaseSysFriend<SysFriend> {
	public static final SysFriend dao = new SysFriend();
	
	/***
	 * 获取我的好友
	 * @param id
	 * @return
	 */
	public List<SysUser> getUserFriend(String id){
		return SysUser.dao.find("select u.* from sys_friend f , sys_user u where f.friend_id = u.id and f.user_id = '"+id+"' ");
	}
}
