package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOaNotice<M extends BaseOaNotice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setSubTitle(java.lang.String subTitle) {
		set("sub_title", subTitle);
		return (M)this;
	}

	public java.lang.String getSubTitle() {
		return get("sub_title");
	}

	public M setSenderId(java.lang.String senderId) {
		set("sender_id", senderId);
		return (M)this;
	}

	public java.lang.String getSenderId() {
		return get("sender_id");
	}

	public M setSenderName(java.lang.String senderName) {
		set("sender_name", senderName);
		return (M)this;
	}

	public java.lang.String getSenderName() {
		return get("sender_name");
	}

	public M setSenderOrgid(java.lang.String senderOrgid) {
		set("sender_orgid", senderOrgid);
		return (M)this;
	}

	public java.lang.String getSenderOrgid() {
		return get("sender_orgid");
	}

	public M setSenderOrgname(java.lang.String senderOrgname) {
		set("sender_orgname", senderOrgname);
		return (M)this;
	}

	public java.lang.String getSenderOrgname() {
		return get("sender_orgname");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public M setPublishTime(java.lang.String publishTime) {
		set("publish_time", publishTime);
		return (M)this;
	}

	public java.lang.String getPublishTime() {
		return get("publish_time");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setToOrgId(java.lang.String toOrgId) {
		set("to_org_id", toOrgId);
		return (M)this;
	}

	public java.lang.String getToOrgId() {
		return get("to_org_id");
	}

	public M setToOrgName(java.lang.String toOrgName) {
		set("to_org_name", toOrgName);
		return (M)this;
	}

	public java.lang.String getToOrgName() {
		return get("to_org_name");
	}

	public M setIfPublish(java.lang.String ifPublish) {
		set("if_publish", ifPublish);
		return (M)this;
	}

	public java.lang.String getIfPublish() {
		return get("if_publish");
	}

}
