package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public M setIsparent(java.lang.String isparent) {
		set("isparent", isparent);
		return (M)this;
	}

	public java.lang.String getIsparent() {
		return get("isparent");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public M setIfShow(java.lang.String ifShow) {
		set("if_show", ifShow);
		return (M)this;
	}

	public java.lang.String getIfShow() {
		return get("if_show");
	}

	public M setPermission(java.lang.String permission) {
		set("permission", permission);
		return (M)this;
	}

	public java.lang.String getPermission() {
		return get("permission");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

}
