package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActRuEventSubscr<M extends BaseActRuEventSubscr<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public M setEventType(java.lang.String eventType) {
		set("EVENT_TYPE_", eventType);
		return (M)this;
	}

	public java.lang.String getEventType() {
		return get("EVENT_TYPE_");
	}

	public M setEventName(java.lang.String eventName) {
		set("EVENT_NAME_", eventName);
		return (M)this;
	}

	public java.lang.String getEventName() {
		return get("EVENT_NAME_");
	}

	public M setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
		return (M)this;
	}

	public java.lang.String getExecutionId() {
		return get("EXECUTION_ID_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public M setActivityId(java.lang.String activityId) {
		set("ACTIVITY_ID_", activityId);
		return (M)this;
	}

	public java.lang.String getActivityId() {
		return get("ACTIVITY_ID_");
	}

	public M setConfiguration(java.lang.String configuration) {
		set("CONFIGURATION_", configuration);
		return (M)this;
	}

	public java.lang.String getConfiguration() {
		return get("CONFIGURATION_");
	}

	public M setCreated(java.util.Date created) {
		set("CREATED_", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("CREATED_");
	}

	public M setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
		return (M)this;
	}

	public java.lang.String getProcDefId() {
		return get("PROC_DEF_ID_");
	}

	public M setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
		return (M)this;
	}

	public java.lang.String getTenantId() {
		return get("TENANT_ID_");
	}

}
