package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOrg<M extends BaseSysOrg<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setVersion(java.lang.Long version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public M setLevel(java.lang.Long level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Long getLevel() {
		return get("level");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public M setIsparent(java.lang.String isparent) {
		set("isparent", isparent);
		return (M)this;
	}

	public java.lang.String getIsparent() {
		return get("isparent");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Long getSort() {
		return get("sort");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public M setOperate(java.lang.String operate) {
		set("operate", operate);
		return (M)this;
	}

	public java.lang.String getOperate() {
		return get("operate");
	}

}
