package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
		return (M)this;
	}

	public java.lang.String getOrgid() {
		return get("orgid");
	}

	public M setStationid(java.lang.String stationid) {
		set("stationid", stationid);
		return (M)this;
	}

	public java.lang.String getStationid() {
		return get("stationid");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
		return (M)this;
	}

	public java.lang.String getIdcard() {
		return get("idcard");
	}

	public M setIsAdmin(java.lang.String isAdmin) {
		set("is_admin", isAdmin);
		return (M)this;
	}

	public java.lang.String getIsAdmin() {
		return get("is_admin");
	}

	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.Long getSort() {
		return get("sort");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

}
