package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOperate<M extends BaseSysOperate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setVersion(java.lang.Long version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public M setPermission(java.lang.String permission) {
		set("permission", permission);
		return (M)this;
	}

	public java.lang.String getPermission() {
		return get("permission");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setOneMany(java.lang.String oneMany) {
		set("one_many", oneMany);
		return (M)this;
	}

	public java.lang.String getOneMany() {
		return get("one_many");
	}

	public M setReturnUrl(java.lang.String returnUrl) {
		set("return_url", returnUrl);
		return (M)this;
	}

	public java.lang.String getReturnUrl() {
		return get("return_url");
	}

	public M setRowFilter(java.lang.String rowFilter) {
		set("row_filter", rowFilter);
		return (M)this;
	}

	public java.lang.String getRowFilter() {
		return get("row_filter");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setModuleId(java.lang.String moduleId) {
		set("module_id", moduleId);
		return (M)this;
	}

	public java.lang.String getModuleId() {
		return get("module_id");
	}

	public M setFormToken(java.lang.String formToken) {
		set("form_token", formToken);
		return (M)this;
	}

	public java.lang.String getFormToken() {
		return get("form_token");
	}

	public M setIpBlack(java.lang.String ipBlack) {
		set("ip_black", ipBlack);
		return (M)this;
	}

	public java.lang.String getIpBlack() {
		return get("ip_black");
	}

	public M setPrivilegess(java.lang.String privilegess) {
		set("privilegess", privilegess);
		return (M)this;
	}

	public java.lang.String getPrivilegess() {
		return get("privilegess");
	}

	public M setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
		return (M)this;
	}

	public java.lang.String getModuleName() {
		return get("module_name");
	}

	public M setSort(java.lang.String sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.lang.String getSort() {
		return get("sort");
	}

}
