package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActIdGroup<M extends BaseActIdGroup<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public M setName(java.lang.String name) {
		set("NAME_", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public M setType(java.lang.String type) {
		set("TYPE_", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("TYPE_");
	}

}
