package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActRuExecution<M extends BaseActRuExecution<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public M setBusinessKey(java.lang.String businessKey) {
		set("BUSINESS_KEY_", businessKey);
		return (M)this;
	}

	public java.lang.String getBusinessKey() {
		return get("BUSINESS_KEY_");
	}

	public M setParentId(java.lang.String parentId) {
		set("PARENT_ID_", parentId);
		return (M)this;
	}

	public java.lang.String getParentId() {
		return get("PARENT_ID_");
	}

	public M setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
		return (M)this;
	}

	public java.lang.String getProcDefId() {
		return get("PROC_DEF_ID_");
	}

	public M setSuperExec(java.lang.String superExec) {
		set("SUPER_EXEC_", superExec);
		return (M)this;
	}

	public java.lang.String getSuperExec() {
		return get("SUPER_EXEC_");
	}

	public M setActId(java.lang.String actId) {
		set("ACT_ID_", actId);
		return (M)this;
	}

	public java.lang.String getActId() {
		return get("ACT_ID_");
	}

	public M setIsActive(java.lang.Integer isActive) {
		set("IS_ACTIVE_", isActive);
		return (M)this;
	}

	public java.lang.Integer getIsActive() {
		return get("IS_ACTIVE_");
	}

	public M setIsConcurrent(java.lang.Integer isConcurrent) {
		set("IS_CONCURRENT_", isConcurrent);
		return (M)this;
	}

	public java.lang.Integer getIsConcurrent() {
		return get("IS_CONCURRENT_");
	}

	public M setIsScope(java.lang.Integer isScope) {
		set("IS_SCOPE_", isScope);
		return (M)this;
	}

	public java.lang.Integer getIsScope() {
		return get("IS_SCOPE_");
	}

	public M setIsEventScope(java.lang.Integer isEventScope) {
		set("IS_EVENT_SCOPE_", isEventScope);
		return (M)this;
	}

	public java.lang.Integer getIsEventScope() {
		return get("IS_EVENT_SCOPE_");
	}

	public M setSuspensionState(java.lang.Integer suspensionState) {
		set("SUSPENSION_STATE_", suspensionState);
		return (M)this;
	}

	public java.lang.Integer getSuspensionState() {
		return get("SUSPENSION_STATE_");
	}

	public M setCachedEntState(java.lang.Integer cachedEntState) {
		set("CACHED_ENT_STATE_", cachedEntState);
		return (M)this;
	}

	public java.lang.Integer getCachedEntState() {
		return get("CACHED_ENT_STATE_");
	}

	public M setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
		return (M)this;
	}

	public java.lang.String getTenantId() {
		return get("TENANT_ID_");
	}

	public M setName(java.lang.String name) {
		set("NAME_", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public M setLockTime(java.util.Date lockTime) {
		set("LOCK_TIME_", lockTime);
		return (M)this;
	}

	public java.util.Date getLockTime() {
		return get("LOCK_TIME_");
	}

}
