package com.pointlion.sys.mvc.admin.generator.generated.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActHiComment<M extends BaseActHiComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public M setType(java.lang.String type) {
		set("TYPE_", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("TYPE_");
	}

	public M setTime(java.util.Date time) {
		set("TIME_", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("TIME_");
	}

	public M setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("USER_ID_");
	}

	public M setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
		return (M)this;
	}

	public java.lang.String getTaskId() {
		return get("TASK_ID_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public M setAction(java.lang.String action) {
		set("ACTION_", action);
		return (M)this;
	}

	public java.lang.String getAction() {
		return get("ACTION_");
	}

	public M setMessage(java.lang.String message) {
		set("MESSAGE_", message);
		return (M)this;
	}

	public java.lang.String getMessage() {
		return get("MESSAGE_");
	}

	public M setFullMsg(byte[] fullMsg) {
		set("FULL_MSG_", fullMsg);
		return (M)this;
	}

	public byte[] getFullMsg() {
		return get("FULL_MSG_");
	}

}
