package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActGeBytearray;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActGeBytearray extends BaseActGeBytearray<ActGeBytearray> {
	public static final ActGeBytearray dao = new ActGeBytearray().dao();
}
