package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActGeProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActGeProperty extends BaseActGeProperty<ActGeProperty> {
	public static final ActGeProperty dao = new ActGeProperty().dao();
}
