package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActHiAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiAttachment extends BaseActHiAttachment<ActHiAttachment> {
	public static final ActHiAttachment dao = new ActHiAttachment().dao();
}
