package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActHiDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiDetail extends BaseActHiDetail<ActHiDetail> {
	public static final ActHiDetail dao = new ActHiDetail().dao();
}
