package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActHiIdentitylink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiIdentitylink extends BaseActHiIdentitylink<ActHiIdentitylink> {
	public static final ActHiIdentitylink dao = new ActHiIdentitylink().dao();
}
