package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActIdGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdGroup extends BaseActIdGroup<ActIdGroup> {
	public static final ActIdGroup dao = new ActIdGroup().dao();
}
