package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActIdUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdUser extends BaseActIdUser<ActIdUser> {
	public static final ActIdUser dao = new ActIdUser().dao();
}
