package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActRuExecution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuExecution extends BaseActRuExecution<ActRuExecution> {
	public static final ActRuExecution dao = new ActRuExecution().dao();
}
