package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActRuTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuTask extends BaseActRuTask<ActRuTask> {
	public static final ActRuTask dao = new ActRuTask().dao();
}
