package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseActRuIdentitylink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuIdentitylink extends BaseActRuIdentitylink<ActRuIdentitylink> {
	public static final ActRuIdentitylink dao = new ActRuIdentitylink().dao();
}
