package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseOaBumph;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaBumph extends BaseOaBumph<OaBumph> {
	public static final OaBumph dao = new OaBumph().dao();
}
