package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseOaNoticeUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaNoticeUser extends BaseOaNoticeUser<OaNoticeUser> {
	public static final OaNoticeUser dao = new OaNoticeUser().dao();
}
