package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseOaNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaNotice extends BaseOaNotice<OaNotice> {
	public static final OaNotice dao = new OaNotice().dao();
}
