package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
}
