package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseSysModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysModule extends BaseSysModule<SysModule> {
	public static final SysModule dao = new SysModule().dao();
}
