package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseSysOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperate extends BaseSysOperate<SysOperate> {
	public static final SysOperate dao = new SysOperate().dao();
}
