package com.pointlion.sys.mvc.admin.generator.generated.model;

import com.pointlion.sys.mvc.admin.generator.generated.model.base.BaseSysRoleoperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleoperator extends BaseSysRoleoperator<SysRoleoperator> {
	public static final SysRoleoperator dao = new SysRoleoperator().dao();
}
