package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaLeave extends BaseOaLeave<OaLeave> {
	public static final OaLeave dao = new OaLeave().dao();
}
