package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaUseCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaUseCar extends BaseOaUseCar<OaUseCar> {
	public static final OaUseCar dao = new OaUseCar().dao();
}
