package com.pointlion.sys.mvc.admin.workflow.model;

import com.pointlion.sys.mvc.common.base.model.BaseVTasklist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VTasklist extends BaseVTasklist<VTasklist> {
	public static final VTasklist dao = new VTasklist();
}
