package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVTasklist<M extends BaseVTasklist<M>> extends Model<M> implements IBean {

	public void setTASKID(java.lang.String TASKID) {
		set("TASKID", TASKID);
	}

	public java.lang.String getTASKID() {
		return get("TASKID");
	}

	public void setINSID(java.lang.String INSID) {
		set("INSID", INSID);
	}

	public java.lang.String getINSID() {
		return get("INSID");
	}

	public void setTASKDEFKEY(java.lang.String TASKDEFKEY) {
		set("TASKDEFKEY", TASKDEFKEY);
	}

	public java.lang.String getTASKDEFKEY() {
		return get("TASKDEFKEY");
	}

	public void setDEFKEY(java.lang.String DEFKEY) {
		set("DEFKEY", DEFKEY);
	}

	public java.lang.String getDEFKEY() {
		return get("DEFKEY");
	}

	public void setDEFNAME(java.lang.String DEFNAME) {
		set("DEFNAME", DEFNAME);
	}

	public java.lang.String getDEFNAME() {
		return get("DEFNAME");
	}

	public void setTASKNAME(java.lang.String TASKNAME) {
		set("TASKNAME", TASKNAME);
	}

	public java.lang.String getTASKNAME() {
		return get("TASKNAME");
	}

	public void setASSIGNEE(java.lang.String ASSIGNEE) {
		set("ASSIGNEE", ASSIGNEE);
	}

	public java.lang.String getASSIGNEE() {
		return get("ASSIGNEE");
	}

	public void setCANDIDATE(java.lang.String CANDIDATE) {
		set("CANDIDATE", CANDIDATE);
	}

	public java.lang.String getCANDIDATE() {
		return get("CANDIDATE");
	}

	public void setDEFID(java.lang.String DEFID) {
		set("DEFID", DEFID);
	}

	public java.lang.String getDEFID() {
		return get("DEFID");
	}

	public void setDELEGATIONID(java.lang.String DELEGATIONID) {
		set("DELEGATIONID", DELEGATIONID);
	}

	public java.lang.String getDELEGATIONID() {
		return get("DELEGATIONID");
	}

	public void setDESCRIPTION(java.lang.String DESCRIPTION) {
		set("DESCRIPTION", DESCRIPTION);
	}

	public java.lang.String getDESCRIPTION() {
		return get("DESCRIPTION");
	}

	public void setCREATETIME(java.lang.String CREATETIME) {
		set("CREATETIME", CREATETIME);
	}

	public java.lang.String getCREATETIME() {
		return get("CREATETIME");
	}

	public void setDUEDATE(java.lang.String DUEDATE) {
		set("DUEDATE", DUEDATE);
	}

	public java.lang.String getDUEDATE() {
		return get("DUEDATE");
	}

}
