package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaNotice<M extends BaseOaNotice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}
	
	public void setSubTitle(java.lang.String title) {
		set("sub_title", title);
	}

	public java.lang.String getSubTitle() {
		return get("sub_title");
	}
	
	public void setSenderId(java.lang.String senderId) {
		set("sender_id", senderId);
	}

	public java.lang.String getSenderId() {
		return get("sender_id");
	}

	public void setSenderName(java.lang.String senderName) {
		set("sender_name", senderName);
	}

	public java.lang.String getSenderName() {
		return get("sender_name");
	}

	public void setSenderOrgId(java.lang.String senderOrgId) {
		set("sender_orgid", senderOrgId);
	}

	public java.lang.String getSenderOrgId() {
		return get("sender_orgid");
	}

	public void setSenderOrgName(java.lang.String senderOrgName) {
		set("sender_orgname", senderOrgName);
	}

	public java.lang.String getSenderOrgName() {
		return get("sender_orgname");
	}

	public void setPublicTime(java.lang.String publishTime) {
		set("publish_time", publishTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getPublishTime() {
		return get("publish_time");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setToOrgId(java.lang.String toOrgId) {
		set("to_org_id", toOrgId);
	}

	public java.lang.String getToOrgId() {
		return get("to_org_id");
	}

	public void setToOrgName(java.lang.String toOrgName) {
		set("to_org_name", toOrgName);
	}

	public java.lang.String getToOrgName() {
		return get("to_org_name");
	}

	public void setIfPublish(java.lang.String ifPublish) {
		set("if_publish", ifPublish);
	}

	public java.lang.String getIfPublish() {
		return get("if_publish");
	}

}
