package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysFriend<M extends BaseSysFriend<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setFriendId(java.lang.String friendId) {
		set("friend_id", friendId);
	}

	public java.lang.String getFriendId() {
		return get("friend_id");
	}

	public void setUserid(java.lang.String user_id) {
		set("user_id", user_id);
	}

	public java.lang.String getUserid() {
		return get("user_id");
	}

}
