package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaResDct<M extends BaseOaResDct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSum(java.lang.Integer sum) {
		set("sum", sum);
	}

	public java.lang.Integer getSum() {
		return get("sum");
	}

	public void setManufactureTime(java.lang.String manufactureTime) {
		set("manufacture_time", manufactureTime);
	}

	public java.lang.String getManufactureTime() {
		return get("manufacture_time");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

}
