package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysCustomSetting<M extends BaseSysCustomSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setBoxLay(java.lang.String boxLay) {
		set("box_lay", boxLay);
	}

	public java.lang.String getBoxLay() {
		return get("box_lay");
	}

	public void setBoxBackImg(java.lang.String boxBackImg) {
		set("box_back_img", boxBackImg);
	}

	public java.lang.String getBoxBackImg() {
		return get("box_back_img");
	}

	public void setAnimate(java.lang.String animate) {
		set("animate", animate);
	}

	public java.lang.String getAnimate() {
		return get("animate");
	}

	public void setAnimateType(java.lang.String animateType) {
		set("animate_type", animateType);
	}

	public java.lang.String getAnimateType() {
		return get("animate_type");
	}

	public void setFixedNavbar(java.lang.String fixedNavbar) {
		set("fixed_navbar", fixedNavbar);
	}

	public java.lang.String getFixedNavbar() {
		return get("fixed_navbar");
	}

	public void setFixedFooter(java.lang.String fixedFooter) {
		set("fixed_footer", fixedFooter);
	}

	public java.lang.String getFixedFooter() {
		return get("fixed_footer");
	}

	public void setFixedNav(java.lang.String fixedNav) {
		set("fixed_nav", fixedNav);
	}

	public java.lang.String getFixedNav() {
		return get("fixed_nav");
	}

	public void setShowUserImg(java.lang.String showUserImg) {
		set("show_user_img", showUserImg);
	}

	public java.lang.String getShowUserImg() {
		return get("show_user_img");
	}

	public void setShowShortCut(java.lang.String showShortCut) {
		set("show_short_cut", showShortCut);
	}

	public java.lang.String getShowShortCut() {
		return get("show_short_cut");
	}

	public void setNavColl(java.lang.String navColl) {
		set("nav_coll", navColl);
	}

	public java.lang.String getNavColl() {
		return get("nav_coll");
	}

	public void setOffType(java.lang.String offType) {
		set("off_type", offType);
	}

	public java.lang.String getOffType() {
		return get("off_type");
	}

	public void setShowAsd(java.lang.String showAsd) {
		set("show_asd", showAsd);
	}

	public java.lang.String getShowAsd() {
		return get("show_asd");
	}

	public void setFixedAsd(java.lang.String fixedAsd) {
		set("fixed_asd", fixedAsd);
	}

	public java.lang.String getFixedAsd() {
		return get("fixed_asd");
	}

	public void setFloatAsd(java.lang.String floatAsd) {
		set("float_asd", floatAsd);
	}

	public java.lang.String getFloatAsd() {
		return get("float_asd");
	}

	public void setLeftAsd(java.lang.String leftAsd) {
		set("left_asd", leftAsd);
	}

	public java.lang.String getLeftAsd() {
		return get("left_asd");
	}

	public void setDarkAsd(java.lang.String darkAsd) {
		set("dark_asd", darkAsd);
	}

	public java.lang.String getDarkAsd() {
		return get("dark_asd");
	}

	public void setColorTheme(java.lang.String colorTheme) {
		set("color_theme", colorTheme);
	}

	public java.lang.String getColorTheme() {
		return get("color_theme");
	}

}
