package com.lion.sys.mvc.role;

import com.lion.sys.mvc.base.model.BaseSysRoleoperator;



/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleoperator extends BaseSysRoleoperator<SysRoleoperator> {
	public static final SysRoleoperator dao = new SysRoleoperator();
}
