package com.lion.sys.mvc.user;

import com.lion.sys.mvc.base.model.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	public static final SysUser dao = new SysUser();
	/***
	 * 根据用户名查询用户
	 * @param username
	 * @return
	 */
	public SysUser findByUsername(String username){
		return dao.findFirst("SELECT * from sys_user u where u.username='"+username+"'");
	}
}
