package com.lion.sys.mvc.user;

import java.util.List;

import com.lion.sys.mvc.base.model.BaseSysUser;
import com.lion.sys.mvc.role.SysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	public static final SysUser dao = new SysUser();
	/***
	 * 根据用户名查询用户
	 * @param username
	 * @return
	 */
	public SysUser findByUsername(String username){
		return dao.findFirst("SELECT * from sys_user u where u.username='"+username+"'");
	}
	
	/***
	 * 获取用户所有的角色
	 */
	public List<SysRole> getAllRole(String id){
		return SysRole.dao.find("select r.* from sys_userrole u ,sys_role r where u.role_id=r.id and u.user_id='"+id+"'");
	}
	
}
