package com.pointlion.sys.mvc.bumph;

import com.pointlion.sys.mvc.base.model.BaseOaBumphOrgUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaBumphOrgUser extends BaseOaBumphOrgUser<OaBumphOrgUser> {
	public static final OaBumphOrgUser dao = new OaBumphOrgUser();
}
